# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openwith < Formula
  desc "macOS TUI for managing default file associations"
  homepage "https://github.com/openwith-org/openwith"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openwith-org/openwith/releases/download/v1.0.0/openwith_1.0.0_darwin_amd64.tar.gz"
      sha256 "0f29b49e48dadda6c5b64b6ce42bcc25cfac4a5422b3d47d11d4e68606dd18c1"

      define_method(:install) do
        bin.install "openwith"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openwith-org/openwith/releases/download/v1.0.0/openwith_1.0.0_darwin_arm64.tar.gz"
      sha256 "65f061eb1e59999fc28eee3dd986ab3684caaaf41ec22fed5b578a9aa651d9a3"

      define_method(:install) do
        bin.install "openwith"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openwith-org/openwith/releases/download/v1.0.0/openwith_1.0.0_linux_amd64.tar.gz"
      sha256 "763756a42a99e193834f2523303f7b5451881fbb0fd25592ff9c98ebf7931afe"
      define_method(:install) do
        bin.install "openwith"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openwith-org/openwith/releases/download/v1.0.0/openwith_1.0.0_linux_arm64.tar.gz"
      sha256 "4ad98a54c219baf3266f5d48970a9549c6d8e61c0117c111c130367aceb52da6"
      define_method(:install) do
        bin.install "openwith"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/openwith --version")
  end
end
